[package]
name = "fontspector-profile-microsoft"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fontspector-checkapi = { path = "../fontspector-checkapi", features = [
    "kurbo",
], version = "1.0.0" }
fontations = { workspace = true }
regex = { workspace = true }
harfrust = { workspace = true }

# For tnum shaping
rustybuzz = "0.20.1"

[lints]
workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
# Plugin architecture
pluginator = { workspace = true }
