[package]
name = "profile-googlefonts"
version = "0.1.0"
edition = "2021"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
glob = "0.3.2"
serde = { workspace = true }                            # For reading shaping check JSON files

[dependencies]
chrono = "0.4.38" # For metadata date checks
fontspector-checkapi = { path = "../fontspector-checkapi", features = [
    "kurbo",
] }
google-fonts-axisregistry = { git = "https://github.com/googlefonts/axisregistry" }
google-fonts-languages = "0"
google-fonts-subsets = { git = "https://github.com/googlefonts/nam-files" }
google-fonts-glyphsets = { git = "https://github.com/googlefonts/glyphsets" }
shaperglot = "1"
indexmap = { workspace = true }
itertools = { workspace = true }
markdown-table = { workspace = true }
protobuf = "3.7.1"
#read-fonts = { workspace = true }
regex = "1.10.6"
serde_json = { workspace = true }
serde = { workspace = true }
skrifa = { workspace = true }
kurbo = { workspace = true }
log = { workspace = true }
num-traits = "0.2.19"
similar = "2.7.0"                 # For shaping check reports, OFL body diff
rustybuzz = { workspace = true }

unicode-normalization = "0"
unicode-properties = { workspace = true }
unicode-canonical-combining-class = "1.0.0"
unicode-script = "0.5.7"
yeslogic-unicode-blocks = "0.2.0"
unicode_names2 = { workspace = true }
write-fonts = { workspace = true }
hashbrown = "0.15.2"

scraper = { version = "0.22.0", default-features = false, features = [
    "errors",
] }
semver = "1.0.25"
image = { version = "0.25.5", default-features = false, features = [
    "png",
    "jpeg",
    "gif",
] }

[build-dependencies]
protobuf-codegen = "3.7.1"
