name: Rust

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          cache-workspace-crates: true
      - name: Build
        run: cargo build
      - name: Install uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
      - name: Run tests
        run: |
          cargo test --verbose --workspace --exclude fontspector-web
          uv venv .venv
          . .venv/bin/activate
          uv pip install maturin pytest
          cd fontspector-py
          maturin build
          uv pip install ../target/wheels/fontspector*.whl
          uv run pytest tests --verbose

  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - run: rustup toolchain install stable --profile default
      - uses: Swatinem/rust-cache@v2
        with:
          cache-workspace-crates: true
      - name: Lint for formatting
        run: cargo fmt --all -- --check
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - run: rustup toolchain install stable --profile default
      - uses: Swatinem/rust-cache@v2
        with:
          cache-workspace-crates: true
      - name: Lint for warnings
        run: cargo clippy --all-targets --all-features -- -D warnings

  wasm-still-builds:
    name: Check that the web site still builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install protobuf-compiler
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build
        run: cd fontspector-web; RUSTFLAGS='-C target-feature=+bulk-memory' wasm-pack build
      - name: Build web site
        run: |
          cd fontspector-web/www
          npm install
          npm run build

  compute-version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v7
      - name: Decide on our version name (tag or "dev")
        id: version
        shell: bash
        run: |
          if [[ "$GITHUB_REF" == refs/tags/fontspector-v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/fontspector-v}"
          else
            VERSION="dev"
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

  deploy-binaries:
    name: Build and upload binaries
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    needs: compute-version
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build-binary.yml
    with:
      version: ${{ needs.compute-version.outputs.version }}
